### ISSUE TITLE
EfLoW installation: Failed to acquire IP address for virtual machine

### ISSUE THREAD

**Issue by FMauroy** [Azure/iotedge-eflow#10]
**Describe the Problem**
I had no issue installing several version of EFLOW on a test system but when I try it at a customer, in a plant, on a test device but in a production environment (OT network), I receive this error: Failed to acquire IP address for virtual machine
I had the issue on the GUI install (through Windows Admin Center and using the PowerShell commands.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install EFLOW on a edge device in the OT network
2. Select External or ICS networking, doesn't matter
3. After a while, you receive the error message. A retry is possible when using the PowerShell method, but doesn't change the result

**Expected behaviour**
EFLOW installs successfully without error.

**Screenshots**
![2021-03-15 11_34_52-FMA - FMA - Remote Desktop Connection](https://user-images.githubusercontent.com/1107417/111161069-02e63b00-859b-11eb-8d2a-158726c302c0.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 IoT Enterprise LTSC
 - Version: 17763
 - Virtual Machine: no
 
**PowerShell output**
`
[03/15/2021 12:16:51] Successfully created virtual machine

[03/15/2021 12:16:52] Querying IP and MAC addresses from virtual machine (BEMOED002-EFLOW)

 - Virtual machine MAC: 00:00:00:00:00:00
 - Failed to acquire IP address for virtual machine

[03/15/2021 12:17:46] Done.

[03/15/2021 12:17:46] Virtual machine hostname: BEMOED002-EFLOW-b283610e

[03/15/2021 12:17:46] ERROR: Could not retrieve MAC or IP address for virtual machine

[03/15/2021 12:17:46] Virtual machine may have failed to acquire an IP address.

Confirmation Required
Do you want to try a fallback to the internal default switch?
Note: This will not destroy the external switch. You can get to back to using the external switch with the command 'Connect-VMNetworkAdapter -SwitchName External -VMname BEMOED002-EFLOW' at any time
later
[Y] Yes  [N] No  [?] Help (default is "Y"):

[03/15/2021 12:21:03] Trying to associate virtual machine with the internal default switch

[03/15/2021 12:21:04] Waiting 5 seconds to allow virtual machine to acquire an IP address

[03/15/2021 12:21:09] Querying IP and MAC addresses from virtual machine (BEMOED002-EFLOW)

 - Virtual machine MAC: 00:15:5d:6a:42:03
 - Failed to acquire IP address for virtual machine

[03/15/2021 12:22:03] Done.

[03/15/2021 12:22:03] ERROR: Retry could not retrieve MAC or IP address for virtual machine (headless)
`

**Comment by fcabrera23** [comment]
@FMauroy,

Could you open the Hyper-V Manager and check if the EFLOW VM has an assigned IP in the networking tab?
If no IP is assigned, could you try restarting the VM?

**Comment by ericvruder** [comment]
@FMauroy 

Have a look at this issue  https://github.com/Azure/iotedge-eflow/issues/9

Sounds very similar to some of the issues we were having. The link includes a workaround for the IP issue, but you might encounter others further down the line.

**Comment by TerryWarwick** [comment]
@FMauroy,

It appears that the VMSwitch which the VM was attempting to use is not able to get an IP address.  On physical hardware this can be caused by a misconfigured VMSwitch that is attempting to use an inactive network connection.  I do not know the specifics of your particular hardware, but I had this occur on my Intel NUC which has two wired connections in addition to a wireless connection.  Once I configured my VMSwitch to use the port that I had connected to the network it resolved this issue for me.  

Please run the following commands in an elevated PowerShell session.

| Description | Command |
|--|--|
| Get Virtual Network Switches  |  ​Get-VMSwitch  | 
| ​Get Network Switch Details | Get-VM \| Where-Object {$_.Name -like '*EFLOW'} \| Get-VMNetworkAdapter |

This will tell you which VMSwitch your EFLOW VM is using as well as how it is configured.  You can modify the configuration of the VMSwitch using Hyper-V Manager using Virtual Switch Manager.  If you are not familiar with Virtual Switch Manager, [this is a pretty decent tutorial ](https://www.veeam.com/blog/how-to-configure-hyper-v-virtual-switch.html#:~:text=Virtual%20Switch%20Manager%20helps%20configure%20vSwitch%20and%20Global,as%20following.%20There%20are%20three%20vSwitch%20types%20available:).

Please let us know how it goes.

Terry Warwick
Microsoft

**Comment by FMauroy** [comment]
Thanks everyone for you quick replies :-) 

I double checked all connections, and didn't find anything wrong. It should have worked. So in the end, I rebooted the host, and it worked right away... Maybe Hyper-V was a bit lost and the reboot set everything straight. I should have rebooted before posting.

Regards
fred
