### ISSUE TITLE
no [agent] / [agent.config] in config.toml by default via Provision-EflowVm

### ISSUE THREAD

**Issue by tahirai-microsoft** [Azure/iotedge-eflow#133]
**Describe the Problem**
no [agent] / [agent.config] in config.toml by default. (making config.toml via Provision-EflowVm)

**To Reproduce**
1, deploy EFLOW-CR and make config,toml via Provision-EflowVm.

**Expected behavior**
should have [agent] / [agent.config] like as below.
> [agent]
> name = "edgeAgent"
> type = "docker"
> imagePullPolicy = "on-create"
> [agent.config]
> image = "mcr.microsoft.com/azureiotedge-agent:1.2"

when we deploy iotedge 1.2 on linux via "sudo iotedge config mp" command, those items were generated by default.

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2020-11#configure-the-iot-edge-agent
this step (to specify [agent.env] and apply) caused error because no [agent] / [agent.config] in config.toml.

**Screenshots**

**Windows Host OS (please complete the following information):**
 - EFLOW-CR (1.2)
 - Edition: tested with Windows 11 Professional
 - Version: 22000.593
 on Surface Pro 5.
 
**Additional context**

**Comment by fcabrera23** [comment]
Hi @tahirai-microsoft,

Thanks for your information. I'm trying to reproduce your issue and will reach back to you soon.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @tahirai-microsoft,

From looking IoT Edge source code, I see that the agent section is commented out in config.toml, and has been for all releases of 1.2. The daemon uses default values that are baked into the code unless the customer uncomments that section in the toml, or otherwise adds it.

So I think the only problem here is that the documentation for 1.2 does not ask the customer to add the section if it is not already present. The IoT Edge team will take care of the documentation.

Thanks,
Francisco
