### ISSUE TITLE
Could not initialize DPS provisioning client after reboot of host-OS

### ISSUE THREAD

**Issue by chokosticks** [Azure/iotedge-eflow#134]
**Describe the bug**
We have multiple devices installed using Eflow and Windows 10.
When a host gets rebooted, the TPM provisioning of the device fails which renders the device useless.

**To Reproduce**
1. Reboot the windows-host.
2. After reboot iotedge gives us, Connection refused (os error 111), when running the command iotedge list

**Expected behavior**
The expected behavior is the device will reprovision when the host starts.

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 PRO
 - Version: 20H2
 - Virtual Machine: EflowVM 1.1.2202.21022
 - Virtual Switch
 - Static IP
 
**Additional context**
We can solve the issue by either running Stop-EflowVM followed by Start-EflowVM.
Or we can solve it by restarting the EFLOW Proxy Service.
Or we can solve it by setting delayed start on the EFLOW Proxy Service.

We can see some troubles under the Event viewer concerning the EFLOWProxy and the operational events.

Attaching logs from a device in state of failure.

[eflowlogs.zip](https://github.com/Azure/iotedge-eflow/files/8470413/eflowlogs.zip)

Is there a configuration we can make without tampering with delayed start?
Is there some timing issues when different services starts after a reboot?

**Comment by fcabrera23** [comment]
Hi @chokosticks,

We are aware of this issue and we plan to fix it in the upcoming EFLOW updates. In the meantime, they are two workarounds that you can evaluate:

1) Change the IoT Edge configuration, so that it's not reprovisioning every time the VM reboots. For more information, check `dynamic_reprovisioning` inside the IoT Edge confg.yaml
2) Check this similar [issue 131](https://github.com/Azure/iotedge-eflow/issues/131) - The user was able to fix this by adding a scheduled task that will periodically ping the EFLOW VM

I hope you're able to use these workarounds, and we will provide a fix as soon as possible.

Thanks,
Francisco

**Comment by Dolphinsimon** [comment]
We have met the same problem in the CR version 1.2.8. But I cannot fix it with #131 or restart EFLOW Proxy Service. Do you have any ideas? @fcabrera23 
Thanks.

**Comment by fcabrera23** [comment]
Hi @Dolphinsimon,

We plan to fix it in our upcoming EFLOW versions for both LTS and CR.  Please check our latest EFLOW release notes.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
@Dolphinsimon,

This should be fixed with our latest update.

Thanks,
Francisco
