### ISSUE TITLE
Sending data between device and a module running in EFLOW

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#15]
A windows IOT enterprise (1809) device needs to have data processed by a module before upload to the cloud.  What are the options for getting that data to the module. 

---
I have a Windows 10 IOT enterprise device (medical device).  We are looking to start managing these devices via IOT Hub and are coming up to speed and trying to uncover best practices.  We would like to be able to create modules for performing various activities.  One such activity is to collect certain data from the main os. (e.g. log files of different types)  In looking at EFLOW it seems that this is the future for IOT Edge running on a Windows 10 device.  

I would like to understand how I pass these logfiles from teh Windows 10 OS where my software runs to control hardware etc to a module that will pre-process them before sending them up to the cloud

My initial going in was: 
If I could collocate my log data on the Windows OS in a particular directory maybe I could mount this particular folder into my module's container and the module could periodically process and upload.  However with EFLOW, it looks like I would have to first mount the folder from windows into the EFLOW VM before it could then be bound or mounted to a module container.  In looking around I'm not sure this is supported?  (I can think of good reasons why it wouldn't be but I just want to be sure)

So this leads me to "module->device adn device->module" messaging, I'd either have to send from the device (and write some code that uses the DeviceClient SDK) and define messages (as I found in teh Windows-iot-samples) to ask for (or send) the log data periodically, for requirement based reasons I don't have to do this constantly so the data becomes "batchy" and fairly large.    but is this really the best/only approach? 

We do have SQL Server installed in the Windows 10 os.  Are modules in EFLOW allowed to talk to that? 

Thanks for helping me learn.. this stuff is all very cool

**Comment by hooligan495** [comment]
ok.. I've been reading more (and noticed issue #3 is a similar question that I have).   If I wanted to share modules and was willing to setup the internal networking properly on my Hyper-V to the EFLOW vm, what do you think of using something like IIS to serve files to modules.  I Don't think it makes sense to support WebDAV adn davfs2 in teh EFLOW vm... but I could build an HTTP client into my module to pull/push data to the host os.  It doesn't feel to elegant to me tbh.  But it's a thought.  (I'm getting some push back from team members on creating anykind of device agent to interop with modules).  

Thanks!

**Comment by TerryWarwick** [comment]
Jay (@hooligan495),

I've been a little slow getting back to you due to a forthcoming change that we have coming in the Azure EFLOW implementation that will remove the ability to use Hyper-V Manager to configure the VM.  This architectural change will lay some groundwork for us to provide support for GPU inside the VM enabling AI/ML scenarios.  

- Would you be interested if we could provide the ability to share a folder on the Windows host with the Linux VM that you could access your log files directly from your module?
- In addition to using the leaf device approach as explained by our samples on http://aka.ms/winiotsamples (soon to be moved over to this repository), it is also possible to use socket communication, but you would also need an agent to act as the sender and your module implemented as a listener.
- IIS does sound like an alternative.
- Have you thought about using the SQL Edge module with Azure EFLOW? 

Terry Warwick
Microsoft

**Comment by hooligan495** [comment]
Hi Terry (@TerryWarwick), 

Thanks for taking the time to respond!  I'd be interested in learning more about the GPU support you mention (Is there anywhere you talk about it? ).  Our Win 10 IOT Enterprise device has a very expensive graphics card in it.  

I think we would be interested in the Share a folder approach for a couple of reasons.  Our device acquires some pretty dense medical imagery (sometimes 100s of GB) and being able to make these files avaialble to modules supports some of our longer term road map plans.    Of course the next question is, what is your timeline for the share a folder?  Days? Months? Quarters?  (I don't need an exact date more a general one)

I will look into SQL Edge to see how it works (I haven't yet).  Would it replace the SQL install we already have?  that'd be interesting.  

THanks for responding!  

All my best!
Jay
