### ISSUE TITLE
external devices/machines should be able to connect directly with the IoT Edge module through the hosts IP address.

### ISSUE THREAD

**Issue by Priyanka-L-Dalawai** [Azure/iotedge-eflow#218]
**Question Summary**
external devices/machines should be able to connect directly with the IoT Edge module through the host's IP address.

**Detailed background**
In the EFLOW hosting a web application/api on the edge Use Case, the end user should be able to access this hosted application anywhere as we have websites deployed and can be accessed anywhere

I read through few comments which were answered for similar issues. But it was not that detail or no documentation is available 
Please help me out with detailed steps on how to achieve the same

**Comment by fcabrera23** [comment]
Hi @Priyanka-L-Dalawai,

Thanks for your question. There are two options available to achieve this

1. Using an External virtual switch during EFLOW deployment, so that the EFLOW VM is directly connected to the external network and hence reachable by external devices/machines.
2. Using Internal/Default Switch and port forwarding configured on the Windows host OS. In this case, the EFLOW VM will be connected to an internal network between the Windows host and the VM, so it won't be reachable/accessible by external devices.  However, you can set up a port forwarding and use the Windows host IP:port to communicate externally to the EFLOW VM. For more information, check [Accessing a WSL 2 distribution from your local area network (LAN)](https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-linux-networking-apps-from-windows-localhost).

I hope that helps,
Francisco

**Comment by Priyanka-L-Dalawai** [comment]
Hi, With Internal/Default Switch  I don't have WSL 2 , have Ethernet tried with that it won't work, Eflow connection itself is stopped.
Tried with external switch creation referring to link 
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-create-virtual-switch?view=iotedge-1.4
net adapter used is ethernet 2
Deployed eflow vm sucessfully (using symmetric keys)
But getting erors on iotedge check, it is not able to list running modules
it throws eror as below issue
https://github.com/Azure/iotedge/issues/6723
Please add detailed steps of creating external switch to solve above errors
And how to access external devices/machines should be able to connect directly with the IoT Edge module through the host's IP address.

**Comment by Priyanka-L-Dalawai** [comment]
Also as suggested above to port redirect while using internal switch don't work as ip of eflow vm will be changing on every restart/start.
Please provide steps for connecting modules outside vm with internal and external switch

**Comment by fcabrera23** [comment]
Hi,

You don't need WSL2 to set up the port forwarding. I was sharing an example of how to set up the port forwarding with EFLOW, using the same guide as WSL.  So there are two possible scenarios

1. Internal Switch with Win Server - you can use Static IP instead of DHCP and then use port forwarding to that static IP.  For example, imagine your EFLOW VM has the 172.20.1.2 address, and you want to forward the port 8080, then on the Windows host OS you should run the following command: `netsh interface portproxy add v4tov4 listenport=8080 listenaddress=0.0.0.0 connectport=8080 connectaddress=172.20.1.2`

1. Default Switch with Win Client- you can use the EFLOW VM hostname + "mshome.net" instead of the static IP.  For example, imagine your EFLOW VM has the "DESKTOP-TEST-EFLOW" hostname, and you want to forward the port 8080, then on the Windows host OS you should run the following command: `netsh interface portproxy add v4tov4 listenport=8080 listenaddress=0.0.0.0 connectport=8080 connectaddress=DESKTOP-TEST-EFLOW.mshome.net`

Thanks,
Francisco

**Comment by Priyanka-L-Dalawai** [comment]
Thanks for the quick reply. I tried 2nd option with connectaddress.
netsh interface portproxy add v4tov4 listenport=8080 listenaddress=20.212.80.254 connectport=8080 connectaddress=eflowvm-eflow.mshome.net
after this I tried to acess it with host ip 20.212.80.254 :8080
Still it didn't return the page I am looking for
with eflowvm-eflow.mshome.net:8080 I am able to access inside host but not outside

**Comment by fcabrera23** [comment]
Hi @Priyanka-L-Dalawai,

A couple of things: 

1. You can start with listenaddress to 0.0.0.0 so that you're listening to all interfaces and then you can narrow it down to a specific IP.
2. Make sure you open the appropriate firewall rule in the Windows host OS
3. Check if you can access the port from the Windows host OS localhost

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @Priyanka-L-Dalawai,

Great to know, so port forwarding is working from the Windows host OS to the EFLOW VM.  To access the port, you need to use the Windows host OS IP, the same one you use to ping the Windows machine from other machines.

Thanks,
Francisco

**Comment by Priyanka-L-Dalawai** [comment]
Thanks, it worked
