### ISSUE TITLE
After File Sharing Feature Docker Engine docker engine Stops, if we stop and start Eflow VM.

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#233]
Hi @fcabrera23 ,

Observing After File Sharing Feature Docker Engine Stops , if we stop and start Eflow VM.

Below are the replication steps .

1. On Windows 11 - 22 H2 - Latest Build (in my case Azure VM create) deploy Eflow Latest Version.

2. Connect Eflow VM (Connect-Eflow). Then go to root "sudo su"

3. issue command "docker version" --> It will print information on "Client" and "Server". Also Docker Service is running.

4. exit from Eflow VM 

5.  On Host machine powershell (in admin mode) execute following lines one by one.

	New-Item "C:\\ProgramData\\AVEVA\\EdgeManagement\\Volumes" -ItemType Directory
	New-Item "C:\\ProgramData\\AVEVA\\EdgeManagement\\Volumes\\sharedFolders.json" -ItemType File
	Set-Content "C:\\ProgramData\\AVEVA\\EdgeManagement\\Volumes\\sharedFolders.json" -Value '[
	   {
			"sharedFolderRoot": "C:\\ProgramData\\AVEVA\\EdgeManagement",
				"sharedFolders": [
					{
						"hostFolderPath": "Volumes",
						"readOnly": false, 
						"targetFolderOnGuest": "/var/lib/docker/volumes"
					}
			]
		}
	]'
	
6.  Add-EflowVmSharedFolder -sharedFoldersJsonPath "C:\\ProgramData\\AVEVA\\EdgeManagement\\Volumes\\sharedFolders.json"
7.  Step 6 establishes file share between host and target machine folders and they are in sync as well. (i.e. if we create folder on host it is reflecting on target folder)
8.  Now execute  "Stop-EflowVm" command on host machine powershell. It stops successfully.
9.  Then execute "Start-EflowVm" command on host machine powershell, it will start successfully.
10. Connect-Eflow machine then execute "docker version" --> it will print ONLY "client" information and "server" information is lost OR docker engine stops working. If we try to create a volume with "docker volume create vishwa"  -->it will fail.

**Note:** **If we do not perform "File Sharing" then  after stop and start of target EflowVm  , docker service runs properly.**

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Thanks for reaching out. We are currently investigating this issue, and we will reach back if we need more information.

Thanks,
Francisco

**Comment by jagadishmurugan** [comment]
Works for me. Are you using version 1.4.4.03034 ?
[cid:f75fa6a5-210a-4999-9b97-6c99f5c3ca3e]
Regards,
Jagadish


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by post2vishwa** [comment]
Hi @jagadishmurugan 

Eflow Version : **1.4.4.03033**  (To install Eflow I followed the steps from the [Create and provision an IoT Edge for Linux on Windows device using symmetric keys - Azure IoT Edge | Microsoft Learn](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-symmetric?view=iotedge-1.4&tabs=azure-portal&viewFallbackFrom=iotedge-2018-06) )  

Attaching terminal messages and screenshot as well.  Reproduction steps remains same.

I am observing Eflow Version : 1.4.4.03034 at GitHub latest release as of today. Is this issue fixed in the next build version.

[Terminal Messages.txt](https://github.com/Azure/iotedge-eflow/files/10938699/Terminal.Messages.txt)

![ScreenShot1](https://user-images.githubusercontent.com/50254283/224227800-4a3bcd04-07fd-4c5f-a269-c56d94446cc5.jpg)

![Available Latest Eflow Version At GitHub](https://user-images.githubusercontent.com/50254283/224227817-c4d4f28d-5413-406f-8d34-d5d9f71e4208.jpg)

Regards,
Vishwa

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

This is not related to `Stop-EflowVm` `Start-EflowVm`. Rather due to mapping `/var/lib/docker/volumes`, which is not recommended. You can verify this by simply restarting docker (systemctl restart docker). When an existing folder is used for FolderSharing (mounting to an existing folder), Linux redirects IO to/from that folder to the mounted device at that location - so the previous contents are effectively hidden. Once folder sharing is reverted, the old folder contents should appear again.

A couple of documents worth looking into it:

- [Docker Storage](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.docker.com%2Fstorage%2F&data=05%7C01%7Cfrancisco.cabrera%40microsoft.com%7C5f4a0610652749e45c4108db3542cae9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638162333267796230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dKJcY4%2FZhePGV2dphhLTKsvzFz3DHT2SX5YIrRPjV5o%3D&reserved=0) -> **Volumes are stored in a part of the host filesystem which is managed by Docker (/var/lib/docker/volumes/ on Linux). Non-Docker processes should not modify this part of the filesystem. Volumes are the best way to persist data in Docker.**
- https://stackoverflow.com/questions/45881820/mount-a-partition-linux-in-a-already-existent-folder
- https://unix.stackexchange.com/questions/198542/what-happens-when-you-mount-over-an-existing-folder-with-contents

Thanks,
Francisco
