### ISSUE TITLE
Connect-EFlowVM / too many authentication failures / edge case for SSH / Solution Found

### ISSUE THREAD

**Issue by codeputer** [Azure/iotedge-eflow#252]
I was using my desktop computer to SSH into at least 10 or more Raspberry PI in the development of an application before starting the install for EFLOW... BTW.. this is the result of about 5 days of intense effort and going down a rabbit hole of Linux, docker, IOT Hub, etc.

Windows 10/11 using the "Default Switch" followed the guidance of: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-symmetric?view=iotedge-1.4&tabs=azure-portal
which resulted in the failure to connect via ssh:
![image](https://github.com/Azure/iotedge-eflow/assets/611541/29c26ffb-b022-48f4-b957-053e0462c26e)

**Expected behavior**
Connection the the VM via SSH, but with NO IPaddress being assigned, that was NOT possible

**Screenshots**
the solution
![image](https://github.com/Azure/iotedge-eflow/assets/611541/26b5c670-060e-4240-83a8-fecb3ba71759)

analysis leading up to the resolution:
![image](https://github.com/Azure/iotedge-eflow/assets/611541/27cd4b12-8944-4488-acff-d5f371436ef1)
![image](https://github.com/Azure/iotedge-eflow/assets/611541/4bab080f-e5d4-42aa-b6c6-d396721aeeba)
![image](https://github.com/Azure/iotedge-eflow/assets/611541/55dfd73a-86da-4c5d-b81c-77dbc02159c9)
![image](https://github.com/Azure/iotedge-eflow/assets/611541/85b1f55f-e5a0-4ce0-b80a-35b6e6c01f09)
![image](https://github.com/Azure/iotedge-eflow/assets/611541/735d42d6-f85f-4e5f-9654-7e0bbd2c41e5)

**Comment by fcabrera23** [comment]
Hi @codeputer,

Thanks for reaching out and sharing your investigation. A couple of things:

1) Our EFLOW VM is not using SSH over TCP/IP; we are using a vSock (Hyper-V socket between the host OS and guest OS) - For more information, see [EFLOW Security](https://learn.microsoft.com/en-us/azure/iot-edge/iot-edge-for-linux-on-windows-security?view=iotedge-1.4). 

2) Because we use vSock, there's no need for an IP address to establish the SSH connection. Also, regular ssh service won't run, and we have our service for vSock connections.

3) Finally, you need authentication; ssh is only enabled for certificate-based auth, and the cert is created and stored during EFLOW installation. 

Thanks,
Francisco
