### ISSUE TITLE
Is it possible to run the Provision-EflowVM command in powershell without administrator access??

### ISSUE THREAD

**Issue by dilipkumar04** [Azure/iotedge-eflow#261]
I am working on a coperate setup. I have deployed the Eflow command in powershell as administrator. What I need to clarify is there any other way to run the Provision-EflowVM command in powershell without administrator access. Can you clarify this. Thank you.

**Comment by fcabrera23** [comment]
Hi @dilipkumar04,

Thanks for reaching out. It's not possible to run EFLOW PS cmdlets without Administrator privilege.  All cmdlets require to run an Admin PowerShell session. This is mainly due to our security posture, allowing only Admin users to interact and modify the lifecycle of the EFLOW VM.

Thanks,
Francisco

**Comment by dilipkumar04** [comment]
Thanks for your support
