### ISSUE TITLE
Command Line does not appear as Tool in Windows Admin Center

### ISSUE THREAD

**Issue by tickledblue3** [Azure/iotedge-eflow#44]
**Describe the bug**
When using Windows Admin Center, the Command Line does not appear as a tool.  Access to the Edge VM command line was very useful for development.

**To Reproduce**
1. In Windows Admin Center, connect to the Azure Edge IoT VM
2. Observe the left hand list only displays Overview. 

**Expected behavior**
Left hand list displays Overview and Command Line

**Windows Host OS:**
- Edition: Windows 10 Enterprise LTSC
- Version: 1809
- Virtual Machine: None (installed on H/W)
 
**Additional context**
This problem occurs more often than not.  Re-installing Azure IoT Edge via Windows Admin Center sometimes resolves the issue, sometimes not.   
This issue was replicated on another Machine with the following Host OS:
- Edition: Windows 10 Pro
- Version: 20H2
- Virtual Machine: None (installed on H/W)

**Comment by TerryWarwick** [comment]
@tickledblue3,

We understand that the Command Shell in Windows Admin Center for EFLOW was useful, but it presented a security risk that we could not continue to support.  We have added a number of PowerShell commands that you can use locally or in a remote desktop session including the ability to invoke a Bash command without leaving PowerShell as well as connect to the VM to show a Bash command shell.  For information on these commands please visit https://aka.ms/AzEFLOW-powershell.

We are still working on our Windows Admin Center extension for EFLOW, which is why you see Preview in the name when you view the installed extension.  We intent to provide more GUI friendly interfaces for common tasks in the future.  Unfortunately this will likely not include a Bash command shell unless we can find a way to securely support credential management for such a tool.

Terry Warwick
Microsoft

**Comment by tickledblue3** [comment]
OK, that's a bit of a disappointment but understandable.   Thanks for the quick response.
