### ISSUE TITLE
Provide performance related documentation

### ISSUE THREAD

**Issue by milijan** [Azure/iotedge-eflow#47]
There are many scenarios to consider for performance but it would be helpful to provide guidelines for general use cases. Such as migrating an app from a Windows container to an Eflow container. Intuitively one might think that linux interop overheads are higher compared to "pure" windows. Or general interop performance between a Windows UI and a backend workload running on windows vs Eflow.

A good place to mention or link to performance considerations might be here:
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-for-linux-on-windows?view=iotedge-2018-06

**Comment by TerryWarwick** [comment]
@milijan,

You are absolutely right that there are many scenarios as well as variables to consider. The challenge is that this is a bit like comparing apples to oranges, they are both round fruit but the similarities end there.  
Although Azure EFLOW does have an overhead of a virtual machine to run Linux-based IoT Edge modules there are benefits.  For instance, the same .Net Core workload packaged as a Linux module is smaller than one packaged as a Windows module due to differences in the operating system architectures.  For IoT Edge devices, this has both footprint as well as in memory benefits to partially offset the virtual machine overhead.
As for interop, performance, it really depends on what you are trying to do, the type of messaging involved etc.  The samples we have here on GitHub show you how to send messages using module identities to the EdgeAgent as well as transforming a USB camera feed into RTSP, but you could also use sockets.  The approach you take depend on what works best for your solution.

Terry Warwick
Microsoft

**Comment by milijan** [comment]
@TerryWarwick thanks! What you have said there about memory is worth mentioning somewhere. Especially since memory is often the bottle neck (keeping more things in cache, containers or High Availability). Anything that may help understand trade-offs is good.

**Comment by nealpeters86** [comment]
Will a 1.1Ghz processor with 4 cores will do just to run eflow etc? We'll just run one small container.

**Comment by fcabrera23** [comment]
> @TerryWarwick thanks! What you have said there about memory is worth mentioning somewhere. Especially since memory is often the bottle neck (keeping more things in cache, containers or High Availability). Anything that may help understand trade-offs is good.

Thanks @milijan, we will consider adding some extra information about memory usage on future updates to our documentation.

**Comment by fcabrera23** [comment]
> Will a 1.1Ghz processor with 4 cores will do just to run eflow etc? We'll just run one small container.

@nealpeters86, 
Please check EFLOW [minimum requirements](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=powershell#prerequisites). We don't have minimum requirements for the CPU speed or cores, so you should check the memory and hard drive requirements.  

Furthermore, it's important to highlight that the amount of RAM that needs to be allocated to the VM is highly dependent on the workload that is being deployed o the VM.
