### ISSUE TITLE
Container on the default network can connect to IoT Hub - Error

### ISSUE THREAD

**Issue by mksp2016** [Azure/iotedge-eflow#55]
**Question Summary**
We are getting below error while running "iotedge check"
![image](https://user-images.githubusercontent.com/34733888/127074565-f6757c3b-92f0-4d88-9169-437d9305f8f2.png)

**Detailed background**

We have installed iotedge-eflow on azure windows VM. hostname is "VMName-EFLOW" in config.yaml, if we use IP address of Eflow VM still we get same error.
Are we missing any network settings? 
here is iotedge check --verbose

![image](https://user-images.githubusercontent.com/34733888/127074947-04f4c42e-1085-4a90-9873-92c6825d08e7.png)

**Comment by fcabrera23** [comment]
Hi @mksp2016,

Thanks for your detailed description of the problem.  I would appreciate it if you could do some tests to get more information.

- Can you try checking your network connectivity and DNS pinging a URL?
- Is your EFLOW host device connected to a locked-down network?  We have found that in some cases, due to network restrictions, EFLOW might try to fall back to a public DNS server, which in some cases is not reachable. If this is the case, can you try the following fix:
1. Open and modify _/etc/systemd/network/99-dhcp-en.network_ 
2. Under [Network], add a new line _DNS=<YOUR_DNS_IP>_
3. Save the file
4. Restart the networking service: `sudo systemctl restart systemd-networkd`
5. Try the `sudo iotedge check --verbose`

**Comment by mksp2016** [comment]
@fcabrera23  Thanks for your response!
We were able to fix it by restarting networking service, however the problem is: 

We are trying to use below sample
https://github.com/Azure/iotedge-eflow/blob/main/samples/interop-textmsg-consoleapp/Documentation/Run%20the%20Console%20Application.MD 

In this case, we are able to send message from Windows to Linux, however Linux to Windows throws error as below, it seems to be a networking issue.

We already allowed set up firewall for Linux as per provided steps: 
![image](https://user-images.githubusercontent.com/34733888/127222446-86a888ea-e3b2-4b93-ab63-85ee7afd0412.png)

We are getting below exception from Module which is throwing while sending message to Windows
![image](https://user-images.githubusercontent.com/34733888/127218597-424f281f-130b-4497-8e03-69735377be22.png)

**Comment by mksp2016** [comment]
We got this fixed by enabling http call from edgeHub, however now our leaf device is coming as unregistered 
Module thorws below error while sending message to windows 
![image](https://user-images.githubusercontent.com/34733888/127247607-7839a839-97e2-4bc7-9341-c4fe3297f650.png)

here are the edgeHub Logs
![image](https://user-images.githubusercontent.com/34733888/127247684-df39b7bd-745e-425a-953e-79281f129ada.png)

**Comment by mksp2016** [comment]
fixed it by making leaf device as IoTEdge device (Not iot device)
