### ISSUE TITLE
Known_hosts file not being generated - IoT Edge install Windows Server 2019

### ISSUE THREAD

**Issue by Mr-Bungles** [Azure/iotedge-eflow#75]
**OS: Windows Server IoT 2019**
**Version 10.0.17763.2145**
**Local VM**

**Description of Problem**
I'm running into an issue when installing IoT Edge on Windows Server IoT 2019. It goes through the steps, creates the Eflow VM, but shows Exception Caught!!! when trying to connect to the VM via SSH. The message I'm seeing is **SSH channel cannot be initialized due to fail to create known hosts file.** 

When installing IoT Edge on a Windows 10 2019 LTSC system, the known_hosts file is automatically created upon install, so I'm not sure what I need to do to generate this file manually. Any assistance is appreciated. Thanks!

**Steps to Reproduce.**
Installed and Enabled Hyper-V
Setup the 'Default Switch' virtual switch
Ran the following powershell commands

_$msiPath = $([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest "https://aka.ms/AzEflowMSI" -OutFile $msiPath
Start-Process -Wait msiexec -ArgumentList "/i","$([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))","/qn"
Deploy-Eflow -acceptEula yes -acceptOptionalTelemetry yes_

![image](https://user-images.githubusercontent.com/90641482/133130573-e114b1c9-2b98-4d23-8f71-d21527d07bca.png)

**Comment by fcabrera23** [comment]
Hi @Mr-Bungles,

Thanks for your information.  It seems that the EFLOW VM was correctly created, but the communication channel failed, probably due to a problem in the "Default Switch".  Could you please provide more information about this switch? Is External or Internal? Have you tested using an External switch?

Thanks,
Francisco

**Comment by Mr-Bungles** [comment]
Hi @fcabrera23 

I tested deploying using Default Switch set to External and received an error noting Default Switch set to internal wasn't present (sorry don't have the exact wording or a screenshot. I can try it again if you need). After the deployment, I've tried switching Default Switch to external, however I still am unable to connect.

At what point in the deployment does "known_hosts" get created?

**Comment by jagadishmurugan** [comment]
Hi @Mr-Bungles ,
Since this is Windows Server 2109 and you setup the 'Default Switch' manually -and it seems you tried Internal & External options. Can you help provide the following information:
1. When 'Default Switch' is set to Internal - for this to work you will need to setup a DHCP/NAT server manually and for Internet connectivity manually configure the EFLOW VM with DNS server
2. External - When you use the External option, i assume you have actually created a External switch named "Default Switch" (via Hyper-V Manager or PowerShell). An External switch is connected to an adapter (which is specified while creating External switch) - Does the host environment have a DHCP server ?

I believe the issue you are reporting is because the EFLOW VM does not have a valid ip address (not on the same network as the adapter on the host). Can you share the output of **"ifconfig** command on the EFLOW VM. You can login to the EFLOW VM using the following cmds:
1. hcsdiag list (lists all HCS VMs)
2. hcsdiag consol EFLOW_VM_ID (use the ID of the wssdagent entry from 'hcsdiag list' output)
3. Also on the host machine, please run "ipconfig /all" and share the output (just the  Default Switch information is sufficient)

Thanks,

**Comment by Mr-Bungles** [comment]
Hi @jagadishmurugan 

Below is the information requested. I see the host Default Switch has a 169 address, so I'm wondering if this possibly is the issue (unless it's supposed to be a local address). 

**EflowVM ifconfig**

_sh-4.4# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:4c:70:d2:8d
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:15:5d:55:5f:74
          inet6 addr: fe80::215:5dff:fe55:5f74/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:20805 errors:0 dropped:618 overruns:0 frame:0
          TX packets:6292 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3586878 (3.5 MB)  TX bytes:1636840 (1.6 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:20360838 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20360838 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1668389797 (1.6 GB)  TX bytes:1668389797 (1.6 GB)_

**Host IPConfig**

_Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-46-51-01
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::1d7d:3d47:9381:7673%12(Preferred)
   Autoconfiguration IPv4 Address. . : 169.254.118.115(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 201332061
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-28-CC-17-88-00-50-56-84-BB-1D
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled_

**Comment by jagadishmurugan** [comment]
Hi @Mr-Bungles ,
Yes. On the host, the interface has a (AutoConfiguration 169.254.x.y) address, and you can see eth0 on the device does not have an IP address. For 'Internal' switch, you will need to setup a DHCP/NAT server manually and for Internet connectivity manually configure the EFLOW VM with DNS server. On Server the easier option is to use an External switch assuming the external network 
 has a DCP server...

Thanks,

**Comment by fcabrera23** [comment]
Hi @Mr-Bungles,

Following @jagadishmurugan  advice, there are two workarounds for your issue

1. Create an Internal Switch with DHCP server, following the [Azure IoT Edge for Linux on Windows virtual switch creation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-virtual-switch?view=iotedge-2018-06) guide.
2. Create an External Switch (with DHCP server on external network), following [External Switch - Example 1](https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vmswitch?view=windowsserver2019-ps#example-1).

Thanks,
Francisco
