### ISSUE TITLE
Can't find file containing SSH key for scp command

### ISSUE THREAD

**Issue by bkarrlander** [Azure/iotedge-eflow#91]
We are looking into having our IoT Edge deployments production ready after a period of testing. One of the TODOs listed in the docs is replacing the test certificates in the VM with production certificates. The ``scp`` option to do this (mentioned here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2018-06&tabs=linux and in some other places) needs an SSH key in a file called ``id_rsa``, but we can't find that file in suggested location:

```
PS C:\Program Files\Azure IoT Edge> ls


    Directory: C:\Program Files\Azure IoT Edge


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2021-11-09     19:29                dda-drivers
d-----        2021-11-09     19:29                mariner-files
d-----        2021-11-09     19:31                yaml
-a----        2021-11-10     10:59     4336910336 AzureIoTEdgeForLinux-v1-EFLOW.vhdx
-a----        2021-11-04     05:23      536492824 AzureIoTEdgeForLinux-v1.cab
-a----        2021-10-28     23:34     2055208960 AzureIoTEdgeForLinux-v1.vhdx
-a----        2021-10-29     00:38      541840805 AzureIoTEdgeForLinux-v1.zip
-a----        2021-11-04     05:23          19215 EFLOWProvider.man
-a----        2021-11-04     05:28         168312 EFLOWProxy.exe
-a----        2021-11-04     05:24          14611 Install-Eflow.ps1
-a----        2021-11-09     19:31            801 known_hosts
-a----        2021-11-04     05:22              0 mariner-update.swu
-a----        2021-11-04     05:26       18541456 nodectl.exe
-a----        2021-11-04     05:24          17557 Uninstall-Eflow.ps1
-a----        2021-11-04     05:24          26702 Update-Script.ps1
-a----        2021-11-04     05:26       38819728 wssdagent.exe
```

**Versions of EFLOW tested**
- 1.1.2110.03111
- 1.1.2109.0

Are we missing something or is this file removed from newer versions of EFLOW?

**A bonus question**: The task of getting production certificates to the VM is not very easy to automate. Will this procedure change in the upcoming version of EFLOW for iotedge v1.2? If so, then maybe we postpone this task until the new version is released.

**Comment by fcabrera23** [comment]
Hi @bkarrlander,

In order to copy files between the Windows host and the EFLOW VM, you can use the PS cmdlet `Copy-EflowVmFile`. For more information, check [EFLOW PowerShell Functions](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06#:~:text=%20PowerShell%20functions%20for%20IoT%20Edge%20for%20Linux,copies%20file%20to%20or%20from%20the...%20More%20).

Also, if you want to set production certificates for IoT Edge, we have a sample PowerShell code to do that. Please check [EFLOW Util](https://github.com/Azure/iotedge-eflow/tree/main/eflow-util). 

Thanks,
Francisco

**Comment by bkarrlander** [comment]
Thank you, @fcabrera23
